// <auto-generated />
using System;
using BikeShop.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BikeShop.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261006192454_AddCustomersAndWorkOrders")]
    partial class AddCustomersAndWorkOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("BikeShop.Api.Domain.Customers.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneDigits")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PhoneDigits");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BikeShop.Api.Domain.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BikeShop.Api.Domain.WorkOrders.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BikeColour")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("BikeMakeModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckedInAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CheckedInByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstimatedLabourMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EstimatedPartsCents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HoldReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LabourRateCentsPerHour")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PosReceiptNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PromisedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StatusChangedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkRequested")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("CheckedInByUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Status");

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("BikeShop.Api.Domain.WorkOrders.WorkOrder", b =>
                {
                    b.HasOne("BikeShop.Api.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BikeShop.Api.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CheckedInByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeShop.Api.Domain.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("BikeShop.Api.Domain.WorkOrders.JobNote", "Notes", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("TEXT");

                            b1.Property<int>("WorkOrderId")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("WrittenAtUtc")
                                .HasColumnType("TEXT");

                            b1.Property<int>("WrittenByUserId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("WorkOrderId");

                            b1.HasIndex("WrittenByUserId");

                            b1.ToTable("JobNotes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderId");

                            b1.HasOne("BikeShop.Api.Domain.Users.User", null)
                                .WithMany()
                                .HasForeignKey("WrittenByUserId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();
                        });

                    b.OwnsMany("BikeShop.Api.Domain.WorkOrders.LabourEntry", "LabourEntries", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("LoggedAtUtc")
                                .HasColumnType("TEXT");

                            b1.Property<int>("MechanicUserId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Minutes")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Note")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT");

                            b1.Property<int>("WorkOrderId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("MechanicUserId");

                            b1.HasIndex("WorkOrderId");

                            b1.ToTable("LabourEntries", (string)null);

                            b1.HasOne("BikeShop.Api.Domain.Users.User", null)
                                .WithMany()
                                .HasForeignKey("MechanicUserId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderId");
                        });

                    b.OwnsMany("BikeShop.Api.Domain.WorkOrders.PartLine", "PartLines", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("AddedAtUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<int>("Quantity")
                                .HasColumnType("INTEGER");

                            b1.Property<long>("UnitPriceCents")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("WorkOrderId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("WorkOrderId");

                            b1.ToTable("PartLines", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderId");
                        });

                    b.Navigation("LabourEntries");

                    b.Navigation("Notes");

                    b.Navigation("PartLines");
                });
#pragma warning restore 612, 618
        }
    }
}
